### ISSUE TITLE
Clarifications in setting up formio with microsoft sql server

### ISSUE THREAD

**Issue by gokuladitya13** [formio/formio-sql#13]
I am trying to integrate formio submission with sql server. I am not able to find info on following things in readme file.  Please clarify following questions:

Can I use it in trial version of formio?
Should I specify settings anywhere else in the repository?
what value should be given for SQL Connector Host URL in form.io project settings?
How do I start formio-sql server?

**Comment by mp3three** [comment]
Thank you for your questions. The answers to these for SQLConnector v2.0.1+ are part of [our documentation](https://form-io.gitbook.io/help/developers/sql-connector/) now
