### ISSUE TITLE
The method form.getRoutes give Internal Server Error response instead of routes

### ISSUE THREAD

**Issue by perumalsamya** [formio/formio-sql#2]
When we execute 'npm start' command, we get the error as in the below image.  The issue is formio.getRoutes method returns the data as "Internal Server Error' but expected the json routes. 

![test](https://user-images.githubusercontent.com/825298/41060720-0ded26e2-69ee-11e8-9e20-195022fa9ca4.png)

**Comment by YuryRybakSoftensity** [comment]
#4
