### ISSUE TITLE
Clarify requirements

### ISSUE THREAD

**Issue by multinerd** [formio/formio-sql#6]
The Readme.md file states

> # Requirements
> The following items are required to use the formio-sql server.
> 1. A Form.io Project on the Team Pro or Commercial Plan

I am using the self-hosted version of Form.io and i'm wondering if i can use this package `formio-sql` to save the data in SQL or if this can only be used with the PaaS version

**Comment by randallknutson** [comment]
This can be used with the hosted (PaaS) or Enterprise Edition of formio.
